config/routes.rb
Rails.application.routes.draw do
  resources :college_applies

  resources :college_registrations

end

app/models/college_apply.rb
class CollegeApply < ActiveRecord::Base
end

app/models/college_registration.rb
class CollegeRegistration < ActiveRecord::Base
  validates :name, :description,  :phone, :email, :college_type, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/college_applies_controller.rb
class CollegeAppliesController < ApplicationController
  before_action :set_college_apply, only: [:show, :edit, :update, :destroy]

  # GET /college_applies
  # GET /college_applies.json
  def index
    @college_applies = CollegeApply.all
  end

  # GET /college_applies/1
  # GET /college_applies/1.json
  def show
  end

  # GET /college_applies/new
  def new
    @college_apply = CollegeApply.new
  end

  # GET /college_applies/1/edit
  def edit
  end

  # POST /college_applies
  # POST /college_applies.json
  def create
    @college_apply = CollegeApply.new(college_apply_params)

    respond_to do |format|
      if @college_apply.save
        format.html { redirect_to @college_apply, notice: 'College apply was successfully created.' }
        format.json { render :show, status: :created, location: @college_apply }
      else
        format.html { render :new }
        format.json { render json: @college_apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /college_applies/1
  # PATCH/PUT /college_applies/1.json
  def update
    respond_to do |format|
      if @college_apply.update(college_apply_params)
        format.html { redirect_to @college_apply, notice: 'College apply was successfully updated.' }
        format.json { render :show, status: :ok, location: @college_apply }
      else
        format.html { render :edit }
        format.json { render json: @college_apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /college_applies/1
  # DELETE /college_applies/1.json
  def destroy
    @college_apply.destroy
    respond_to do |format|
      format.html { redirect_to college_applies_url, notice: 'College apply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college_apply
      @college_apply = CollegeApply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_apply_params
      params.require(:college_apply).permit(:name, :course, :college_session, :apply_date)
    end
end

app/controllers/college_registrations_controller.rb
class CollegeRegistrationsController < ApplicationController
  before_action :set_college_registration, only: [:show, :edit, :update, :destroy]

  # GET /college_registrations
  # GET /college_registrations.json
  def index
    @college_registrations = CollegeRegistration.all
  end

  # GET /college_registrations/1
  # GET /college_registrations/1.json
  def show
  end

  # GET /college_registrations/new
  def new
    @college_registration = CollegeRegistration.new
  end

  # GET /college_registrations/1/edit
  def edit
  end

  # POST /college_registrations
  # POST /college_registrations.json
  def create
    @college_registration = CollegeRegistration.new(college_registration_params)

    respond_to do |format|
      if @college_registration.save
        format.html { redirect_to @college_registration, notice: 'College registration was successfully created.' }
        format.json { render :show, status: :created, location: @college_registration }
      else
        format.html { render :new }
        format.json { render json: @college_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /college_registrations/1
  # PATCH/PUT /college_registrations/1.json
  def update
    respond_to do |format|
      if @college_registration.update(college_registration_params)
        format.html { redirect_to @college_registration, notice: 'College registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @college_registration }
      else
        format.html { render :edit }
        format.json { render json: @college_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /college_registrations/1
  # DELETE /college_registrations/1.json
  def destroy
    @college_registration.destroy
    respond_to do |format|
      format.html { redirect_to college_registrations_url, notice: 'College registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college_registration
      @college_registration = CollegeRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_registration_params
      params.require(:college_registration).permit(:name, :description, :adress, :phone, :email, :college_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/college_applies_helper.rb
module CollegeAppliesHelper
end

app/helpers/college_registrations_helper.rb
module CollegeRegistrationsHelper
end

app/views/college_applies/_form.html.erb
<%= form_for(@college_apply) do |f| %>
  <% if @college_apply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college_apply.errors.count, "error") %> prohibited this college_apply from being saved:</h2>

      <ul>
      <% @college_apply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :college_session %><br>
    <%= f.text_field :college_session %>
  </div>
  <div class="field">
    <%= f.label :apply_date %><br>
    <%= f.text_field :apply_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/college_applies/edit.html.erb
<h1>Editing College Apply</h1>

<%= render 'form' %>

<%= link_to 'Show', @college_apply %> |
<%= link_to 'Back', college_applies_path %>

app/views/college_applies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing College Applies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Course</th>
      <th>College session</th>
      <th>Apply date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @college_applies.each do |college_apply| %>
      <tr>
        <td><%= college_apply.name %></td>
        <td><%= college_apply.course %></td>
        <td><%= college_apply.college_session %></td>
        <td><%= college_apply.apply_date %></td>
        <td><%= link_to 'Show', college_apply %></td>
        <td><%= link_to 'Edit', edit_college_apply_path(college_apply) %></td>
        <td><%= link_to 'Destroy', college_apply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College apply', new_college_apply_path %>

app/views/college_applies/new.html.erb
<h1>New College Apply</h1>

<%= render 'form' %>

<%= link_to 'Back', college_applies_path %>

app/views/college_applies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college_apply.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @college_apply.course %>
</p>

<p>
  <strong>College session:</strong>
  <%= @college_apply.college_session %>
</p>

<p>
  <strong>Apply date:</strong>
  <%= @college_apply.apply_date %>
</p>

<%= link_to 'Edit', edit_college_apply_path(@college_apply) %> |
<%= link_to 'Back', college_applies_path %>

app/views/college_registrations/_form.html.erb
<%= form_for(@college_registration) do |f| %>
  <% if @college_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college_registration.errors.count, "error") %> prohibited this college_registration from being saved:</h2>

      <ul>
      <% @college_registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_field :adress %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :college_type %><br>
    <%= f.text_field :college_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/college_registrations/edit.html.erb
<h1>Editing College Registration</h1>

<%= render 'form' %>

<%= link_to 'Show', @college_registration %> |
<%= link_to 'Back', college_registrations_path %>

app/views/college_registrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing College Registrations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Adress</th>
      <th>Phone</th>
      <th>Email</th>
      <th>College type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @college_registrations.each do |college_registration| %>
      <tr>
        <td><%= college_registration.name %></td>
        <td><%= college_registration.description %></td>
        <td><%= college_registration.adress %></td>
        <td><%= college_registration.phone %></td>
        <td><%= college_registration.email %></td>
        <td><%= college_registration.college_type %></td>
        <td><%= link_to 'Show', college_registration %></td>
        <td><%= link_to 'Edit', edit_college_registration_path(college_registration) %></td>
        <td><%= link_to 'Destroy', college_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College registration', new_college_registration_path %>

app/views/college_registrations/new.html.erb
<h1>New College Registration</h1>

<%= render 'form' %>

<%= link_to 'Back', college_registrations_path %>

app/views/college_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college_registration.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @college_registration.description %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @college_registration.adress %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @college_registration.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @college_registration.email %>
</p>

<p>
  <strong>College type:</strong>
  <%= @college_registration.college_type %>
</p>

<%= link_to 'Edit', edit_college_registration_path(@college_registration) %> |
<%= link_to 'Back', college_registrations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>College</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>